# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "7-cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build API
        working-directory: ./api
        run: go build

      - name: Test API
        working-directory: ./api
        run: go test -v ./...

      - name: Build CLI
        working-directory: ./cli
        run: go build

      - name: Test CLI
        working-directory: ./cli
        run: go test -v ./...