# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "7-cicd" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Build API
        working-directory: ./api
        run: go build

      - name: Test API
        working-directory: ./api
        run: go test -v ./...

      - name: Build CLI
        working-directory: ./cli
        run: go build

      - name: Test CLI
        working-directory: ./cli
        run: go test -v ./...

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Generate tag
        id: generate_tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./api/api
          asset_name: api-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip

      - name: Upload CLI Release Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cli/cli
          asset_name: cli-${{ env.TAG_NAME }}.zip
          asset_content_type: application/zip